import pygame

EVENT_CONFIRM = pygame.USEREVENT + 1
EVENT_CANCEL = pygame.USEREVENT + 2
EVENT_DIRECTION = pygame.USEREVENT + 3
EVENT_ZOOM_MINUS = pygame.USEREVENT + 4
EVENT_ZOOM_PLUS = pygame.USEREVENT + 5
